#ifndef Tests_h
#define Tests_h

  #include <Arduino.h>
  #include "LoggerA.h"
  
  #include "Utils.h"
  #include "AVRConstants.h"
  #include "TargetProgramDetector.h"
  #include "ConfFile.h"

  // nothing is required to run these tests (no special connections to Arduino Nano)
  void testUtilsGen();
  void __testConvertByteToHexChar();
  void __testConvertHexCharToByte();
  void __testConvertTwoHexCharsToByte();
  void __testConvert3DigitsToInt();
  void __testIsWhiteChar();
  void __testIsValidNameChar();
  void __testStrLength();

  // nothing is required to run these tests (no special connections to Arduino Nano)
  void testUtilsAVR();
  void __testGetAVRModelIdBySignature();
  void __testGetAVRModelAndConf();
  void __testGetAVRModelNameById();
  void __testGetAVRModelIdByName();


  // requires A0,A1,A2,A3 and A4 connections, depending on type of test
  void testTargetProgramDetector();
  void __testOneWireID(int d);
  void __testGetProgId(int d);
  

  // 1) requires SD Card to be connected (see ConfFile.h for more details)
  // 2) requires test files to be written to SD card
  void testConfFile();
  void __testAutogenerateDirNamesByProgId();
  void __testSkipToValidData();
  void __testReadRootConfFile();
  // doesn't support strings longer then 125 characters!
  boolean __testStringMatches(const char* str1, const char* str2, boolean debugMode);

#endif
